# https://hub.docker.com/_/mysql
# test용 db
version: "3.8"                                    # docker-compose 파일 버전입니다.
services: # 서비스들을 선언합니다.
  mysql: # 서비스명을 선언합니다.
    container_name: fastcampus-db
    image: mysql:8.0.30
    volumes: # {호스트}:{컨테이너}
      - ./db/conf.d:/etc/mysql/conf.d             # MySQL 설정 파일이 있습니다.
    ports: # 외부로 노출시킬 port 입니다.
      - "3307:3306"
    environment: # 환경 변수
      - MYSQL_DATABASE=fastcampus
      - MYSQL_USER=conny
      - MYSQL_PASSWORD=conny123
      - MYSQL_ROOT_PASSWORD=conny123
      - TZ=Asia/Seoul
  postgres:
    container_name: postgre-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=fastcampus
      - POSTGRES_USER=conny
      - POSTGRES_PASSWORD=conny123